version: 2

models:
# -------------------------
# STAGING MODELS
# -------------------------
  - name: stg_customers
    description: "Cleaned and standardized customer data."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "Name of the customer."
        tests:
          - not_null

      - name: city
        description: "Customer's city."
        tests:
          - not_null

      - name: updated_at
        description: "Timestamp indicating when the customer record was last updated."
        tests:
          - not_null
