version: 2

seeds:
  - name: raw_customers
  - name: raw_orders
  - name: sales_data
  - name: sales_flat
  - name: dim_customer
  - name: dim_customers
  - name: dim_date_seed
  - name: dim_product
  - name: fact_sales