version: 2
seeds:
  - name: raw_customers
    config:
      column_types:
        customer_id: integer
        customer_name: text
        city: text
        updated_at: "timestamp without time zone"

  - name: raw_orders
    config:
      column_types:
        order_id: integer
        order_date: date
        customer_id: integer
        order_amount: "numeric(10,2)"
        status: text
        updated_at: "timestamp without time zone"

  - name: sales_data
    config:
      column_types:
        order_id: integer
        product_name: text
        category: text
        quantity: integer
        unit_price: "numeric(10,2)"
        order_date: date

  - name: sales_flat
    config:
      column_types:
        sales_id: integer
        units_sold: integer
        total_amount: "numeric(10,2)"
        date_key: date
        year: integer
        month: integer
        product_name: text
        category: text
        sub_category: text
        customer_name: text
        region: text
        city: text

  - name: dim_customer_seed
    config:
      column_types:
        customer_key: integer
        customer_name: text
        region: text
        city: text

  - name: dim_customers_seed
    config:
      column_types:
        customer_id: integer
        customer_name: text
        city: text
        updated_at: "timestamp without time zone"
        dbt_scd_id: text
        dbt_updated_at: "timestamp without time zone"
        dbt_valid_from: "timestamp without time zone"
        dbt_valid_to: "timestamp without time zone"

  - name: dim_date_seed
    config:
      column_types:
        date_key: date
        year: integer
        month: integer
        day: integer
        weekday: text

  - name: dim_product_seed
    config:
      column_types:
        product_key: integer
        product_name: text
        category: text
        brand: text

  - name: fact_sales
    config:
      column_types:
        sales_id: integer
        date_key: date
        product_key: integer
        customer_key: integer
        units_sold: integer
        total_amount: "numeric(10,2)"