name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dbt-postgres
        run: pip install "dbt-postgres>=1.11,<1.12"

      - name: Create dbt profiles directory
        run: mkdir -p ~/.dbt

      - name: Write profiles.yml
        run: |
          cat <<EOF > ~/.dbt/profiles.yml
          demo_project:
            target: ci
            outputs:
              ci:
                type: postgres
                host: "${{ secrets.DBT_HOST }}"
                user: "${{ secrets.DBT_USER }}"
                password: "${{ secrets.DBT_PASSWORD }}"
                port: ${{ secrets.DBT_PORT }}
                dbname: "${{ secrets.DBT_DBNAME }}"
                schema: demo_project
                threads: 4
                sslmode: require
          EOF

      - name: Debug connection
        run: dbt debug

      - name: Run dbt build
        run: dbt build